services:
  - type: web
    name: online-vlc
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000
